<?php

/**
 * Demo partner platforms seeded by PlatformSeeder (13 tenants).
 */
return [
    [
        'name' => 'Excellence Leads UK',
        'slug' => 'excellence-uk',
        'timezone' => 'Europe/London',
        'default_country' => 'GB',
        'default_currency' => 'GBP',
        'admin_email' => 'uk@powerbyexcellence.test',
        'buyers' => ['Aviva Direct Leads', 'Admiral Insurance Partners', 'LV= Partner Desk'],
        'suppliers' => ['LeadFlow Media Group', 'Affiliate Horizon UK'],
        'campaigns' => [
            ['name' => 'Auto Insurance', 'reference' => 'auto-insurance-uk', 'vertical' => 'insurance_auto'],
            ['name' => 'Loans', 'reference' => 'loans-uk', 'vertical' => 'loans'],
            ['name' => 'Mortgage', 'reference' => 'mortgage-uk', 'vertical' => 'mortgage'],
            ['name' => 'Solar', 'reference' => 'solar-uk', 'vertical' => 'solar'],
            ['name' => 'Payday Loans', 'reference' => 'payday-loans-uk', 'vertical' => 'payday_loans'],
            ['name' => 'Home Insurance', 'reference' => 'home-insurance-uk', 'vertical' => 'insurance_home'],
        ],
    ],
    [
        'name' => 'Partner Leads US',
        'slug' => 'partner-solar-us',
        'domain' => 'solar-us.powerbyexcellence.test',
        'timezone' => 'America/New_York',
        'default_country' => 'US',
        'default_currency' => 'USD',
        'admin_email' => 'us@powerbyexcellence.test',
        'buyers' => ['State Farm Lead Exchange', 'Progressive Partner Network', 'Allstate Buyers'],
        'suppliers' => ['QuoteCompare Affiliates', 'Solar Media Partners'],
        'campaigns' => [
            ['name' => 'Auto Insurance', 'reference' => 'auto-insurance-us', 'vertical' => 'insurance_auto'],
            ['name' => 'Personal Loans', 'reference' => 'loans-us', 'vertical' => 'loans'],
            ['name' => 'Mortgage', 'reference' => 'mortgage-us', 'vertical' => 'mortgage'],
            ['name' => 'Payday Loans', 'reference' => 'payday-loans-us', 'vertical' => 'payday_loans'],
            ['name' => 'Solar', 'reference' => 'solar-us', 'vertical' => 'solar'],
            ['name' => 'Medicare', 'reference' => 'medicare-us', 'vertical' => 'medicare'],
            ['name' => 'Debt Relief', 'reference' => 'debt-us', 'vertical' => 'debt_relief'],
            ['name' => 'Legal', 'reference' => 'legal-us', 'vertical' => 'legal'],
        ],
    ],
    [
        'name' => 'Pacific Finance AU',
        'slug' => 'finance-au',
        'timezone' => 'Australia/Sydney',
        'default_country' => 'AU',
        'default_currency' => 'AUD',
        'admin_email' => 'au@powerbyexcellence.test',
        'buyers' => ['Sydney Finance Buyers', 'Melbourne Loan Desk'],
        'suppliers' => ['Oz Affiliate Network'],
        'campaigns' => [
            ['name' => 'Personal Loans', 'reference' => 'loans-au', 'vertical' => 'loans'],
            ['name' => 'Mortgage', 'reference' => 'mortgage-au', 'vertical' => 'mortgage'],
            ['name' => 'Solar', 'reference' => 'solar-au', 'vertical' => 'solar'],
        ],
    ],
    [
        'name' => 'Euro Leads DE',
        'slug' => 'euro-de',
        'timezone' => 'Europe/Berlin',
        'default_country' => 'DE',
        'default_currency' => 'EUR',
        'admin_email' => 'de@powerbyexcellence.test',
        'buyers' => ['Berlin Buyers GmbH', 'Munich Lead Exchange'],
        'suppliers' => ['DACH Affiliates'],
        'campaigns' => [
            ['name' => 'Loans', 'reference' => 'loans-de', 'vertical' => 'loans'],
            ['name' => 'Home Improvement', 'reference' => 'home-improve-de', 'vertical' => 'home_improvement'],
            ['name' => 'Life Insurance', 'reference' => 'life-de', 'vertical' => 'insurance_life'],
            ['name' => 'Education', 'reference' => 'education-de', 'vertical' => 'education'],
        ],
    ],
    [
        'name' => 'Medicare Leads US',
        'slug' => 'medicare-us',
        'timezone' => 'America/Chicago',
        'default_country' => 'US',
        'default_currency' => 'USD',
        'admin_email' => 'medicare@powerbyexcellence.test',
        'buyers' => ['Senior Care Buyers', 'Medicare Advantage Partners'],
        'suppliers' => ['Health Affiliate Co'],
        'campaigns' => [
            ['name' => 'Medicare Advantage', 'reference' => 'medicare-adv', 'vertical' => 'medicare'],
            ['name' => 'Final Expense', 'reference' => 'final-expense', 'vertical' => 'insurance_life'],
            ['name' => 'ACA Health', 'reference' => 'aca-health', 'vertical' => 'healthcare'],
        ],
    ],
    [
        'name' => 'Home Services UK',
        'slug' => 'home-uk',
        'timezone' => 'Europe/London',
        'default_country' => 'GB',
        'default_currency' => 'GBP',
        'admin_email' => 'home@powerbyexcellence.test',
        'buyers' => ['Trades Buyer Network', 'HomePro Partners'],
        'suppliers' => ['Trade Affiliate Hub'],
        'campaigns' => [
            ['name' => 'Solar', 'reference' => 'solar-home-uk', 'vertical' => 'solar'],
            ['name' => 'Home Improvement', 'reference' => 'home-improve-uk', 'vertical' => 'home_improvement'],
            ['name' => 'Moving', 'reference' => 'moving-uk', 'vertical' => 'moving'],
            ['name' => 'Home Insurance', 'reference' => 'home-ins-home-uk', 'vertical' => 'insurance_home'],
        ],
    ],
    [
        'name' => 'Legal Leads US',
        'slug' => 'legal-us',
        'timezone' => 'America/Los_Angeles',
        'default_country' => 'US',
        'default_currency' => 'USD',
        'admin_email' => 'legal@powerbyexcellence.test',
        'buyers' => ['PI Attorney Network', 'Mass Tort Buyers'],
        'suppliers' => ['Legal Affiliate Media'],
        'campaigns' => [
            ['name' => 'Personal Injury', 'reference' => 'pi-us', 'vertical' => 'legal'],
            ['name' => 'Mass Tort', 'reference' => 'mass-tort-us', 'vertical' => 'legal'],
            ['name' => 'Auto Insurance', 'reference' => 'auto-legal-us', 'vertical' => 'insurance_auto'],
        ],
    ],
    [
        'name' => 'Education Leads UK',
        'slug' => 'education-uk',
        'timezone' => 'Europe/London',
        'default_country' => 'GB',
        'default_currency' => 'GBP',
        'admin_email' => 'edu@powerbyexcellence.test',
        'buyers' => ['University Partners', 'Online Course Buyers'],
        'suppliers' => ['Edu Affiliate Network'],
        'campaigns' => [
            ['name' => 'Higher Education', 'reference' => 'higher-ed-uk', 'vertical' => 'education'],
            ['name' => 'Loans', 'reference' => 'student-loans-uk', 'vertical' => 'loans'],
            ['name' => 'Payday Loans', 'reference' => 'payday-ed-uk', 'vertical' => 'payday_loans'],
        ],
    ],
    [
        'name' => 'Canada Insurance',
        'slug' => 'insurance-ca',
        'timezone' => 'America/Toronto',
        'default_country' => 'CA',
        'default_currency' => 'CAD',
        'admin_email' => 'ca@powerbyexcellence.test',
        'buyers' => ['Toronto Buyers', 'Vancouver Insurance Desk'],
        'suppliers' => ['Maple Affiliate Group'],
        'campaigns' => [
            ['name' => 'Auto Insurance', 'reference' => 'auto-ca', 'vertical' => 'insurance_auto'],
            ['name' => 'Home Insurance', 'reference' => 'home-ca', 'vertical' => 'insurance_home'],
            ['name' => 'Mortgage', 'reference' => 'mortgage-ca', 'vertical' => 'mortgage'],
            ['name' => 'Solar', 'reference' => 'solar-ca', 'vertical' => 'solar'],
        ],
    ],
    [
        'name' => 'EMEA Loans',
        'slug' => 'emea-loans',
        'timezone' => 'Europe/Amsterdam',
        'default_country' => 'NL',
        'default_currency' => 'EUR',
        'admin_email' => 'emea@powerbyexcellence.test',
        'buyers' => ['Amsterdam Buyers', 'Brussels Finance Partners'],
        'suppliers' => ['EU Lead Affiliates'],
        'campaigns' => [
            ['name' => 'Personal Loans', 'reference' => 'loans-emea', 'vertical' => 'loans'],
            ['name' => 'Payday Loans', 'reference' => 'payday-emea', 'vertical' => 'payday_loans'],
            ['name' => 'Debt Relief', 'reference' => 'debt-emea', 'vertical' => 'debt_relief'],
            ['name' => 'Mortgage', 'reference' => 'mortgage-emea', 'vertical' => 'mortgage'],
            ['name' => 'Auto Insurance', 'reference' => 'auto-emea', 'vertical' => 'insurance_auto'],
            ['name' => 'Solar', 'reference' => 'solar-emea', 'vertical' => 'solar'],
        ],
    ],
    [
        'name' => 'France Leads FR',
        'slug' => 'france-fr',
        'timezone' => 'Europe/Paris',
        'default_country' => 'FR',
        'default_currency' => 'EUR',
        'admin_email' => 'fr@powerbyexcellence.test',
        'subscription_plan' => 'growth',
        'buyers' => ['AXA France Partners', 'MAIF Lead Desk'],
        'suppliers' => ['Hexagone Affiliés', 'LeadSud Media'],
        'campaigns' => [
            ['name' => 'Assurance Auto', 'reference' => 'auto-fr', 'vertical' => 'insurance_auto'],
            ['name' => 'Prêts Personnels', 'reference' => 'loans-fr', 'vertical' => 'loans'],
            ['name' => 'Solaire', 'reference' => 'solar-fr', 'vertical' => 'solar'],
            ['name' => 'Assurance Habitation', 'reference' => 'home-fr', 'vertical' => 'insurance_home'],
        ],
    ],
    [
        'name' => 'Iberia Leads ES',
        'slug' => 'spain-es',
        'timezone' => 'Europe/Madrid',
        'default_country' => 'ES',
        'default_currency' => 'EUR',
        'admin_email' => 'es@powerbyexcellence.test',
        'subscription_plan' => 'starter',
        'buyers' => ['Mapfre Partners', 'Santander Lead Hub'],
        'suppliers' => ['Iberia Affiliates'],
        'campaigns' => [
            ['name' => 'Seguros Auto', 'reference' => 'auto-es', 'vertical' => 'insurance_auto'],
            ['name' => 'Préstamos', 'reference' => 'loans-es', 'vertical' => 'loans'],
            ['name' => 'Hipoteca', 'reference' => 'mortgage-es', 'vertical' => 'mortgage'],
        ],
    ],
    [
        'name' => 'Asia Finance SG',
        'slug' => 'singapore-sg',
        'timezone' => 'Asia/Singapore',
        'default_country' => 'SG',
        'default_currency' => 'SGD',
        'admin_email' => 'sg@powerbyexcellence.test',
        'subscription_plan' => 'enterprise',
        'buyers' => ['DBS Lead Partners', 'OCBC Buyer Network', 'UOB Affiliates'],
        'suppliers' => ['SEA Lead Media', 'APAC Compare'],
        'campaigns' => [
            ['name' => 'Personal Loans', 'reference' => 'loans-sg', 'vertical' => 'loans'],
            ['name' => 'Home Loans', 'reference' => 'mortgage-sg', 'vertical' => 'mortgage'],
            ['name' => 'Solar', 'reference' => 'solar-sg', 'vertical' => 'solar'],
            ['name' => 'Insurance', 'reference' => 'insurance-sg', 'vertical' => 'insurance_auto'],
        ],
    ],
];
