<?php

return [
    'insurance_auto' => [
        'label' => 'Auto Insurance',
        'description' => 'Motor insurance lead capture with vehicle and driver fields.',
        'default_floor' => 12,
        'default_payout' => 5,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'vehicle_year', 'label' => 'Vehicle Year', 'required' => true, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'vehicle_make', 'label' => 'Vehicle Make', 'required' => false, 'ping_field' => true],
            ['name' => 'current_insurer', 'label' => 'Current Insurer', 'required' => false, 'ping_field' => true],
        ],
    ],
    'loans' => [
        'label' => 'Loans',
        'description' => 'Personal and unsecured loan applications.',
        'default_floor' => 8,
        'default_payout' => 4,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'loan_amount', 'label' => 'Loan Amount', 'required' => true, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'loan_purpose', 'label' => 'Loan Purpose', 'required' => false, 'ping_field' => true],
            ['name' => 'credit_score', 'label' => 'Credit Score Band', 'required' => false, 'ping_field' => true],
        ],
    ],
    'mortgage' => [
        'label' => 'Mortgage',
        'description' => 'Purchase and remortgage lead capture.',
        'default_floor' => 15,
        'default_payout' => 7,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'property_value', 'label' => 'Property Value', 'required' => true, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'loan_amount', 'label' => 'Mortgage Amount', 'required' => true, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'employment_status', 'label' => 'Employment Status', 'required' => false, 'ping_field' => true],
        ],
    ],
    'payday_loans' => [
        'label' => 'Payday Loans',
        'description' => 'Short-term payday and high-acceptance loan leads.',
        'default_floor' => 6,
        'default_payout' => 3,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'loan_amount', 'label' => 'Loan Amount', 'required' => true, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'monthly_income', 'label' => 'Monthly Income', 'required' => true, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'employment_status', 'label' => 'Employment Status', 'required' => false, 'ping_field' => true],
        ],
    ],
    'solar' => [
        'label' => 'Solar',
        'description' => 'Residential and commercial solar installation leads.',
        'default_floor' => 10,
        'default_payout' => 5,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'home_owner', 'label' => 'Home Owner', 'required' => true, 'ping_field' => true, 'type' => 'select'],
            ['name' => 'electric_bill', 'label' => 'Monthly Electric Bill', 'required' => false, 'ping_field' => true, 'type' => 'number'],
            ['name' => 'roof_type', 'label' => 'Roof Type', 'required' => false, 'ping_field' => true],
        ],
    ],
    'insurance_home' => [
        'label' => 'Home Insurance',
        'description' => 'Homeowners and renters insurance quotes.',
        'default_floor' => 11,
        'default_payout' => 5,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'property_type', 'label' => 'Property Type', 'required' => true, 'ping_field' => true],
            ['name' => 'cover_type', 'label' => 'Cover Type', 'required' => false, 'ping_field' => true],
        ],
    ],
    'insurance_life' => [
        'label' => 'Life Insurance',
        'description' => 'Term and whole life insurance applications.',
        'default_floor' => 14,
        'default_payout' => 7,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'date_of_birth', 'label' => 'Date of Birth', 'required' => true, 'ping_field' => true],
            ['name' => 'coverage_amount', 'label' => 'Coverage Amount', 'required' => false, 'ping_field' => true, 'type' => 'number'],
        ],
    ],
    'medicare' => [
        'label' => 'Medicare',
        'description' => 'Medicare Advantage and supplement leads.',
        'default_floor' => 18,
        'default_payout' => 9,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'ZIP Code', 'required' => true, 'ping_field' => true],
            ['name' => 'date_of_birth', 'label' => 'Date of Birth', 'required' => true, 'ping_field' => true],
            ['name' => 'medicare_id', 'label' => 'Medicare ID', 'required' => false, 'ping_field' => true],
        ],
    ],
    'healthcare' => [
        'label' => 'Healthcare',
        'description' => 'ACA and health plan enrollment leads.',
        'default_floor' => 12,
        'default_payout' => 6,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'ZIP Code', 'required' => true, 'ping_field' => true],
            ['name' => 'household_size', 'label' => 'Household Size', 'required' => true, 'ping_field' => true, 'type' => 'number'],
        ],
    ],
    'debt_relief' => [
        'label' => 'Debt Relief',
        'description' => 'Debt consolidation and settlement inquiries.',
        'default_floor' => 9,
        'default_payout' => 4,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'debt_amount', 'label' => 'Total Debt', 'required' => true, 'ping_field' => true, 'type' => 'number'],
        ],
    ],
    'legal' => [
        'label' => 'Legal',
        'description' => 'Personal injury and legal case intake.',
        'default_floor' => 20,
        'default_payout' => 10,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'case_type', 'label' => 'Case Type', 'required' => true, 'ping_field' => true],
            ['name' => 'incident_date', 'label' => 'Incident Date', 'required' => false, 'ping_field' => true],
        ],
    ],
    'education' => [
        'label' => 'Education',
        'description' => 'University and online course enrollment leads.',
        'default_floor' => 7,
        'default_payout' => 3,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'program_interest', 'label' => 'Program Interest', 'required' => true, 'ping_field' => true],
            ['name' => 'education_level', 'label' => 'Education Level', 'required' => false, 'ping_field' => true],
        ],
    ],
    'home_improvement' => [
        'label' => 'Home Improvement',
        'description' => 'Windows, roofing, HVAC and renovation leads.',
        'default_floor' => 10,
        'default_payout' => 5,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'project_type', 'label' => 'Project Type', 'required' => true, 'ping_field' => true],
            ['name' => 'home_owner', 'label' => 'Home Owner', 'required' => true, 'ping_field' => true],
        ],
    ],
    'moving' => [
        'label' => 'Moving',
        'description' => 'Residential and commercial moving quotes.',
        'default_floor' => 8,
        'default_payout' => 4,
        'fields' => [
            ['name' => 'firstname', 'label' => 'First Name', 'required' => true, 'ping_field' => false],
            ['name' => 'lastname', 'label' => 'Last Name', 'required' => true, 'ping_field' => false],
            ['name' => 'email', 'label' => 'Email', 'required' => true, 'ping_field' => false],
            ['name' => 'phone1', 'label' => 'Phone', 'required' => true, 'ping_field' => false],
            ['name' => 'zipcode', 'label' => 'From Postcode', 'required' => true, 'ping_field' => true],
            ['name' => 'move_date', 'label' => 'Move Date', 'required' => true, 'ping_field' => true],
            ['name' => 'move_size', 'label' => 'Move Size', 'required' => false, 'ping_field' => true],
        ],
    ],
];
